# Generated by Django 5.0 on 2023-12-31 05:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("staffs", "0004_alter_staff_quali"),
    ]

    operations = [
        migrations.RenameField(
            model_name="staff",
            old_name="firstname",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="other_name",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="others",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="surname",
        ),
    ]
