# Generated by Django 5.0 on 2023-12-31 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staffs", "0005_rename_firstname_staff_name_remove_staff_other_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="aadhar_card",
            field=models.ImageField(
                blank=True, upload_to="staff/certificates/", verbose_name="Aadhar Card"
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="certificate_submited",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Aadhar card", "Aadhar card"),
                    ("Degree certificate", "Degree certificate"),
                    ("Resume", "Resume"),
                ],
                max_length=1024,
                verbose_name="Submited Certificate",
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="community",
            field=models.CharField(
                choices=[
                    ("OC", "OC"),
                    ("BC", "BC"),
                    ("MBC", "MBC"),
                    ("ST/SC", "ST/SC"),
                    ("others", "others"),
                ],
                default="OC",
                max_length=524,
                verbose_name="Community",
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="degree_certificate",
            field=models.ImageField(
                blank=True,
                upload_to="staff/certificates/",
                verbose_name="Degree Certificate",
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="email",
            field=models.EmailField(default="", max_length=254, verbose_name="Email"),
        ),
        migrations.AddField(
            model_name="staff",
            name="last_salary",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Last Job Salary drawn"
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="passport",
            field=models.ImageField(
                blank=True, upload_to="staff/passports/", verbose_name="Photo"
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="religion",
            field=models.CharField(
                choices=[
                    ("Hindu", "Hindu"),
                    ("Christian", "Christian"),
                    ("Muslim", "Muslim"),
                    ("others", "others"),
                ],
                default="Hindu",
                max_length=554,
                verbose_name="Religion",
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="resume",
            field=models.ImageField(
                blank=True, upload_to="staff/certificates/", verbose_name="Resume"
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="software_pro",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Software Proficiency"
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="staff_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Administrative staff", "Administrative staff"),
                    ("Acadamic Staff", "Acadamic Staff"),
                ],
                max_length=1024,
                verbose_name="Staff Role",
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="study_colleg",
            field=models.CharField(
                blank=True, max_length=1024, verbose_name="College Name"
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="study_year",
            field=models.IntegerField(
                blank=True, default=None, verbose_name="If undergoing Year"
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="working_exp",
            field=models.TextField(
                blank=True, null=True, verbose_name="Working Experience"
            ),
        ),
    ]
