# Generated by Django 5.0 on 2023-12-31 06:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("staffs", "0006_staff_aadhar_card_staff_certificate_submited_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staff",
            name="certificate_submited",
        ),
    ]
