# Generated by Django 5.0 on 2023-12-31 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staffs", "0007_remove_staff_certificate_submited"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="passport",
            field=models.ImageField(
                blank=True, upload_to="staff/certificates/", verbose_name="Photo"
            ),
        ),
    ]
