# Generated by Django 5.0 on 2023-12-31 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staffs", "0008_alter_staff_passport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="quali",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Qualification"
            ),
        ),
    ]
