# Generated by Django 4.2 on 2023-04-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="Bill_No",
            field=models.CharField(default=None, max_length=245),
        ),
    ]
