# Generated by Django 5.0 on 2023-12-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0006_alter_invoice_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="received_by",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Recived By"
            ),
        ),
    ]
