# Generated by Django 5.0 on 2023-12-30 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0008_alter_invoice_student_alter_invoiceitem_invoice_and_more"),
        ("students", "0033_alter_bookmodel_student_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="student",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="students.student",
            ),
        ),
    ]
