# Generated by Django 5.0 on 2023-12-31 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0010_alter_invoiceitem_invoice_alter_receipt_invoice"),
        ("staffs", "0010_alter_staff_study_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipt",
            name="received_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="staffs.staff",
                verbose_name="Billing Staff",
            ),
        ),
    ]
