# Generated by Django 5.0 on 2023-12-30 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursebookmodel",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="course.coursemodel"
            ),
        ),
        migrations.AlterField(
            model_name="coursesubjectmodel",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="course.coursemodel"
            ),
        ),
    ]
