# Generated by Django 5.0 on 2023-12-30 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("corecode", "0007_alter_book_name"),
        ("course", "0002_alter_coursebookmodel_course_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coursesubjectmodel",
            name="sub_duration",
        ),
        migrations.AlterField(
            model_name="coursebookmodel",
            name="book_name",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="corecode.book",
            ),
        ),
        migrations.AlterField(
            model_name="coursesubjectmodel",
            name="sub_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="corecode.subject"
            ),
        ),
    ]
