# Generated by Django 5.0 on 2023-12-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("corecode", "0007_alter_book_name"),
        ("course", "0003_remove_coursesubjectmodel_sub_duration_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coursebookmodel",
            name="book_name",
        ),
        migrations.RemoveField(
            model_name="coursesubjectmodel",
            name="sub_name",
        ),
        migrations.AddField(
            model_name="coursebookmodel",
            name="book_name",
            field=models.ManyToManyField(to="corecode.book"),
        ),
        migrations.AddField(
            model_name="coursesubjectmodel",
            name="sub_name",
            field=models.ManyToManyField(to="corecode.subject"),
        ),
    ]
