# Generated by Django 5.0 on 2023-12-31 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("corecode", "0008_exam"),
        ("course", "0004_remove_coursebookmodel_book_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseExamModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="course.coursemodel",
                    ),
                ),
                ("course_exams", models.ManyToManyField(to="corecode.exam")),
            ],
        ),
    ]
