# Generated by Django 5.0 on 2023-12-27 10:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enquiry", "0012_alter_enquirylogs_exp_date"),
        ("students", "0002_auto_20201124_0614"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={"ordering": ["enrol_no"]},
        ),
        migrations.RemoveField(
            model_name="student",
            name="current_class",
        ),
        migrations.RemoveField(
            model_name="student",
            name="firstname",
        ),
        migrations.RemoveField(
            model_name="student",
            name="other_name",
        ),
        migrations.RemoveField(
            model_name="student",
            name="others",
        ),
        migrations.RemoveField(
            model_name="student",
            name="parent_mobile_number",
        ),
        migrations.RemoveField(
            model_name="student",
            name="registration_number",
        ),
        migrations.RemoveField(
            model_name="student",
            name="surname",
        ),
        migrations.AddField(
            model_name="student",
            name="aadhar_no",
            field=models.BigIntegerField(
                blank=True, default=None, null=True, verbose_name="Aadhar Number"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="age",
            field=models.IntegerField(
                blank=True, default=None, null=True, verbose_name="Age"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="class_time",
            field=models.CharField(
                default="2pm - 4pm", max_length=255, verbose_name="Class Timinig"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="course",
            field=models.CharField(
                default="HDCA", max_length=1024, verbose_name="Course To Join"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="email",
            field=models.EmailField(default="", max_length=254, verbose_name="Email"),
        ),
        migrations.AddField(
            model_name="student",
            name="enrol_no",
            field=models.IntegerField(default=None, verbose_name="Enrollment Number"),
        ),
        migrations.AddField(
            model_name="student",
            name="if_enq",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="enquiry.enquiry",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="mobile_number",
            field=models.CharField(
                blank=True,
                max_length=13,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Entered mobile number isn't in a right format!",
                        regex="^[0-9]{10,15}$",
                    )
                ],
                verbose_name="Mobile Number",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="occupation",
            field=models.CharField(
                choices=[
                    ("Employed", "Employed"),
                    ("Unemployed", "Unemployed"),
                    ("Housewife", "Housewife"),
                    ("Businessman", "Businessman"),
                    ("Student", "Student"),
                    ("Others", "Others"),
                ],
                default="Student",
                max_length=1024,
                verbose_name="Student Occupation",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="rel_name",
            field=models.CharField(
                default=None, max_length=255, verbose_name="Father/Husband Name"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="rel_occupation",
            field=models.CharField(
                default=None, max_length=255, verbose_name="Father/Husband Occupation"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="student_company_name",
            field=models.CharField(
                blank=True,
                max_length=1024,
                null=True,
                verbose_name="If Emloyed Company Name",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="student_name",
            field=models.CharField(
                default=None, max_length=255, verbose_name="Student Name"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="total_fee",
            field=models.IntegerField(default=0, verbose_name="Total Fees"),
        ),
        migrations.AlterField(
            model_name="student",
            name="address",
            field=models.TextField(blank=True, verbose_name="Address"),
        ),
        migrations.AlterField(
            model_name="student",
            name="date_of_birth",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Date of Birth"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                default="male",
                max_length=10,
                verbose_name="Gender",
            ),
        ),
    ]
