# Generated by Django 5.0 on 2023-12-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "students",
            "0003_alter_student_options_remove_student_current_class_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="enrol_no",
            field=models.IntegerField(default=0, verbose_name="Enrollment Number"),
        ),
    ]
