# Generated by Django 5.0 on 2023-12-27 15:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0004_alter_student_enrol_no"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="age",
        ),
        migrations.RemoveField(
            model_name="student",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="student",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="student",
            name="mobile_number",
        ),
        migrations.RemoveField(
            model_name="student",
            name="occupation",
        ),
        migrations.RemoveField(
            model_name="student",
            name="rel_name",
        ),
        migrations.RemoveField(
            model_name="student",
            name="student_company_name",
        ),
        migrations.RemoveField(
            model_name="student",
            name="student_name",
        ),
    ]
