# Generated by Django 5.0 on 2023-12-27 19:49

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0006_remove_student_address_remove_student_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="age",
            field=models.IntegerField(blank=True, default=None, verbose_name="Age"),
        ),
        migrations.AddField(
            model_name="student",
            name="community",
            field=models.CharField(
                choices=[
                    ("OC", "OC"),
                    ("BC", "BC"),
                    ("MBC", "MBC"),
                    ("ST/SC", "ST/SC"),
                ],
                default="OC",
                max_length=524,
                verbose_name="Student Community",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="date_of_birth",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Date of Birth"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="email",
            field=models.EmailField(default="", max_length=254, verbose_name="Email"),
        ),
        migrations.AddField(
            model_name="student",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                default="male",
                max_length=10,
                verbose_name="Gender",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="mobile_number",
            field=models.CharField(
                blank=True,
                max_length=13,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Entered mobile number isn't in a right format!",
                        regex="^[0-9]{10,15}$",
                    )
                ],
                verbose_name="Mobile Number",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="occupation",
            field=models.CharField(
                choices=[
                    ("Employed", "Employed"),
                    ("Unemployed", "Unemployed"),
                    ("Housewife", "Housewife"),
                    ("Businessman", "Businessman"),
                    ("Student", "Student"),
                    ("Others", "Others"),
                ],
                default="Student",
                max_length=1024,
                verbose_name="Student Occupation",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="rel_name",
            field=models.CharField(
                default=None, max_length=255, verbose_name="Father/Husband Name"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="religion",
            field=models.CharField(
                choices=[
                    ("Hindu", "Hindu"),
                    ("Christian", "Christian"),
                    ("Muslim", "Muslim"),
                ],
                default="Hindu",
                max_length=554,
                verbose_name="Student Religion",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="student_company_name",
            field=models.CharField(
                blank=True,
                max_length=1024,
                null=True,
                verbose_name="If Emloyed Company Name",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="student_name",
            field=models.CharField(
                default="", max_length=255, verbose_name="Student Name"
            ),
        ),
    ]
