# Generated by Django 5.0 on 2023-12-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0008_alter_student_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="address",
            field=models.TextField(blank=True, verbose_name="Address"),
        ),
    ]
