# Generated by Django 5.0 on 2023-12-28 03:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0007_alter_student_rel_occupation"),
        ("students", "0009_student_address"),
    ]

    operations = []
