# Generated by Django 5.0 on 2023-12-28 04:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0010_merge_20231228_0921"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="rel_occupation",
            field=models.CharField(
                default=None, max_length=255, verbose_name="Father/Husband Occupation"
            ),
        ),
    ]
