# Generated by Django 5.0 on 2023-12-28 04:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0011_alter_student_rel_occupation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="community",
            field=models.CharField(
                choices=[
                    ("OC", "OC"),
                    ("BC", "BC"),
                    ("MBC", "MBC"),
                    ("ST/SC", "ST/SC"),
                ],
                default="OC",
                max_length=524,
                verbose_name="Community",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="passport",
            field=models.ImageField(
                blank=True, upload_to="students/passports/", verbose_name="Photo"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="religion",
            field=models.CharField(
                choices=[
                    ("Hindu", "Hindu"),
                    ("Christian", "Christian"),
                    ("Muslim", "Muslim"),
                ],
                default="Hindu",
                max_length=554,
                verbose_name="Religion",
            ),
        ),
    ]
