# Generated by Django 5.0 on 2023-12-28 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0013_alter_student_enrol_no"),
    ]

    operations = [
        migrations.CreateModel(
            name="Classmodel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bookmodel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "received_book",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=2046,
                        verbose_name="Received Book",
                    ),
                ),
                (
                    "received_date",
                    models.DateTimeField(verbose_name="Book received Date"),
                ),
                (
                    "received_by",
                    models.CharField(max_length=255, verbose_name="Received By"),
                ),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.student",
                    ),
                ),
            ],
        ),
    ]
