# Generated by Django 5.0 on 2023-12-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0014_classmodel_bookmodel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookmodel",
            name="received_by",
        ),
        migrations.AddField(
            model_name="bookmodel",
            name="handled_by",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Handled By"
            ),
        ),
    ]
