# Generated by Django 5.0 on 2023-12-28 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0015_remove_bookmodel_received_by_bookmodel_handled_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmodel",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="students.student"
            ),
        ),
    ]
