# Generated by Django 5.0 on 2023-12-28 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0018_alter_classmodel_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmodel",
            name="received_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 28, 15, 30),
                verbose_name="Book received Date",
            ),
        ),
    ]
