# Generated by Django 5.0 on 2023-12-28 11:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0019_alter_bookmodel_received_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exammodel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True, default=None, max_length=355, verbose_name="Subject"
                    ),
                ),
                (
                    "exam_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Examed date"
                    ),
                ),
                (
                    "contected_mode",
                    models.CharField(
                        blank=True,
                        choices=[("Online", "Online"), ("Offline", "Offline")],
                        max_length=255,
                        verbose_name="Contected mode",
                    ),
                ),
                ("mark", models.FloatField(blank=True, verbose_name="Mark")),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.student",
                    ),
                ),
            ],
        ),
    ]
