# Generated by Django 5.0 on 2023-12-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0021_alter_student_enrol_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="enrol_no",
            field=models.IntegerField(
                default=0, unique=True, verbose_name="Enrollment Number"
            ),
        ),
    ]
