# Generated by Django 5.0 on 2023-12-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0022_alter_student_enrol_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="district",
            field=models.CharField(
                blank=True, default=None, max_length=255, verbose_name="District"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="pincode",
            field=models.IntegerField(blank=True, default=None, verbose_name="Pincode"),
        ),
        migrations.AddField(
            model_name="student",
            name="remark",
            field=models.CharField(
                blank=True, default=None, max_length=500, verbose_name="Remark"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="taluka",
            field=models.CharField(
                blank=True, default=None, max_length=255, verbose_name="Taluk"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="community",
            field=models.CharField(
                choices=[
                    ("OC", "OC"),
                    ("BC", "BC"),
                    ("MBC", "MBC"),
                    ("ST/SC", "ST/SC"),
                    ("others", "others"),
                ],
                default="OC",
                max_length=524,
                verbose_name="Community",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="course",
            field=models.CharField(
                default="HDCA", max_length=1024, verbose_name="Course"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female"), ("others", "others")],
                default="male",
                max_length=10,
                verbose_name="Gender",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="religion",
            field=models.CharField(
                choices=[
                    ("Hindu", "Hindu"),
                    ("Christian", "Christian"),
                    ("Muslim", "Muslim"),
                    ("others", "others"),
                ],
                default="Hindu",
                max_length=554,
                verbose_name="Religion",
            ),
        ),
    ]
