# Generated by Django 5.0 on 2023-12-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0024_classmodel_class_time_exammodel_paratical_mark_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classmodel",
            name="class_time",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="Class Time",
            ),
        ),
    ]
