# Generated by Django 5.0 on 2023-12-28 17:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0027_alter_bookmodel_received_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmodel",
            name="received_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Book received Date"
            ),
        ),
    ]
