# Generated by Django 5.0 on 2023-12-29 04:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "students",
            "0029_bookmodel_last_updated_certificatemodel_last_updated_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="address1",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="Address Line 2",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="address2",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="Address Line 3",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="address",
            field=models.CharField(
                blank=True, default=None, max_length=255, verbose_name="Address"
            ),
        ),
    ]
