# Generated by Django 5.0 on 2023-12-30 09:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0031_remove_student_student_name_student_studenat_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="studenat_name",
            new_name="student_name",
        ),
    ]
