# Generated by Django 5.0 on 2023-12-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0034_alter_bookmodel_handled_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classmodel",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="Ended on"),
        ),
    ]
