# Generated by Django 5.0 on 2023-12-31 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("corecode", "0009_time"),
        ("students", "0035_alter_classmodel_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classmodel",
            name="class_time",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="corecode.time",
                verbose_name="Class Timing",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="class_time",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="corecode.time",
                verbose_name="Class Timing",
            ),
        ),
    ]
