# Generated by Django 5.0.3 on 2024-03-09 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corecode", "0009_time"),
        ("students", "0037_alter_classmodel_class_time_alter_student_class_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmodel",
            name="received_book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="corecode.book"
            ),
        ),
    ]
