# Generated by Django 3.0.5 on 2020-05-06 14:20

from django.db import migrations
from django.contrib.auth.models import User
import datetime


def default_site_config(apps, schema_editor):
    """Default site configurations"""

    User.objects.create_superuser("csc", "logi@logi.com", "csc")

    Config = apps.get_model("corecode", "SiteConfig")
    Config.objects.bulk_create(
        [
    
            Config(key="Institute", value="COMPUTER SOFTWARE COLLEGE"),
        ]
    )

    Session = apps.get_model("corecode", "AcademicSession")
    Session.objects.bulk_create(
        [
            Session(name="Virudhachalam", current=True),
        ]
    )

    Term = apps.get_model("corecode", "AcademicTerm")
    Term.objects.bulk_create(
        [
            Term(name=f"{datetime.datetime.now().year}", current=True),
        ]
    )

    Subject = apps.get_model("corecode", "Subject")

    StudentClass = apps.get_model("corecode", "StudentClass")
    StudentClass.objects.bulk_create(
        [
            StudentClass(name="HDCA"),
            StudentClass(name="DCA"),
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ("corecode", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(default_site_config),
    ]
