# Generated by Django 5.0 on 2023-12-31 03:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("corecode", "0007_alter_book_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200, unique=True)),
                (
                    "exam_mode",
                    models.CharField(
                        choices=[("Online", "online"), ("Offline", "Offline")],
                        default="Offline",
                        max_length=255,
                    ),
                ),
                ("exam_duration", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
