# Generated by Django 5.0 on 2023-12-31 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("corecode", "0008_exam"),
    ]

    operations = [
        migrations.CreateModel(
            name="Time",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "ordering": ["time"],
            },
        ),
    ]
