# Generated by Django 4.2 on 2023-04-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("revenue", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="revenue",
            name="Total_paid",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="revenue",
            name="Total_student",
            field=models.IntegerField(default=None),
        ),
    ]
