# Generated by Django 5.0 on 2023-12-30 17:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("course", "0004_remove_coursebookmodel_book_name_and_more"),
        ("staffs", "0004_alter_staff_quali"),
        ("students", "0033_alter_bookmodel_student_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BatchModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        max_length=255,
                        verbose_name="Batch Status",
                    ),
                ),
                (
                    "Batch_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Batch Id"
                    ),
                ),
                (
                    "batch_start_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Batch Start Date",
                    ),
                ),
                (
                    "batch_end_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Batch End Date"
                    ),
                ),
                (
                    "batch_timing",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Batch Timing"
                    ),
                ),
                (
                    "Batch_course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="course.coursemodel",
                    ),
                ),
                (
                    "batch_staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="staffs.staff"
                    ),
                ),
                ("batch_students", models.ManyToManyField(to="students.student")),
            ],
            options={
                "ordering": ["-batch_start_date"],
            },
        ),
    ]
