# Generated by Django 5.0 on 2023-12-30 18:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("batch", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="batchmodel",
            old_name="Batch_course",
            new_name="batch_course",
        ),
        migrations.RenameField(
            model_name="batchmodel",
            old_name="Batch_id",
            new_name="batch_id",
        ),
    ]
