# Generated by Django 5.0 on 2023-12-31 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("batch", "0002_rename_batch_course_batchmodel_batch_course_and_more"),
        ("corecode", "0008_exam"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batchmodel",
            name="batch_course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="corecode.subject"
            ),
        ),
        migrations.AlterField(
            model_name="batchmodel",
            name="batch_end_date",
            field=models.DateField(
                blank=True, default=None, null=True, verbose_name="Batch End Date"
            ),
        ),
    ]
