# Generated by Django 5.0 on 2023-12-31 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("batch", "0004_alter_batchmodel_batch_course"),
        ("students", "0035_alter_classmodel_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batchmodel",
            name="batch_students",
            field=models.ManyToManyField(blank=True, null=True, to="students.student"),
        ),
    ]
