# Generated by Django 5.0 on 2023-12-31 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("batch", "0005_alter_batchmodel_batch_students"),
        ("corecode", "0009_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batchmodel",
            name="batch_timing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="corecode.time",
                verbose_name="Class Timing",
            ),
        ),
    ]
