# Generated by Django 5.0 on 2023-12-31 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("batch", "0007_alter_batchmodel_batch_timing"),
        ("students", "0037_alter_classmodel_class_time_alter_student_class_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batchmodel",
            name="batch_students",
            field=models.ManyToManyField(blank=True, to="students.student"),
        ),
    ]
