# Generated by Django 5.0 on 2023-12-26 06:45

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Enquiry",
            fields=[
                ("auto_increment", models.AutoField(primary_key=True, serialize=False)),
                (
                    "enquiry_no",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="Enquiry Number",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="", max_length=255, verbose_name="Student Name"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="Address")),
                (
                    "pincode",
                    models.IntegerField(
                        blank=True, default=666666, verbose_name="pincode"
                    ),
                ),
                (
                    "mobile_number",
                    models.CharField(
                        default=0,
                        max_length=13,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Entered mobile number isn't in a right format!",
                                regex="^[0-9]{10,15}$",
                            )
                        ],
                        verbose_name="Mobile Number",
                    ),
                ),
                (
                    "email",
                    models.EmailField(default="", max_length=254, verbose_name="Email"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")],
                        default="male",
                        max_length=10,
                        verbose_name="gender",
                    ),
                ),
                (
                    "qualification",
                    models.TextField(default="", verbose_name="Qualification"),
                ),
                (
                    "qualification_status",
                    models.CharField(
                        choices=[
                            ("Completed", "Completed"),
                            ("Undergoing", "Undergoing"),
                        ],
                        default="Completed",
                        max_length=50,
                        verbose_name="Qualification status",
                    ),
                ),
                ("studying_year", models.IntegerField(verbose_name="Studying year")),
                (
                    "studying_course",
                    models.TextField(
                        default="", max_length=255, verbose_name="Studying course"
                    ),
                ),
                (
                    "student_role",
                    models.CharField(
                        choices=[
                            ("Employed", "Employed"),
                            ("Unemployed", "Unemployed"),
                            ("Housewife", "Housewife"),
                            ("Businessman", "Businessman"),
                            ("Student", "Student"),
                            ("Others", "Others"),
                        ],
                        default="Student",
                        max_length=1024,
                        verbose_name="Student occupation",
                    ),
                ),
                (
                    "need_of_study",
                    models.CharField(
                        choices=[
                            ("For a job", "For a job"),
                            (
                                "For a job in software profession",
                                "For a job in software profession",
                            ),
                            ("For advance study", "For advance study"),
                            ("Sponsored by company", "Sponsored by company"),
                        ],
                        default="For a job",
                        max_length=1024,
                        verbose_name="Need of study",
                    ),
                ),
                (
                    "course_to_join",
                    models.CharField(
                        default="",
                        max_length=1024,
                        verbose_name="Course intersted to join",
                    ),
                ),
                ("time_to_study", models.CharField(default="", max_length=255)),
                (
                    "known_csc",
                    models.CharField(
                        choices=[
                            ("Televison", "Televison"),
                            ("newspaper", "newspaper"),
                            ("friend recommend", "friend recommend"),
                            ("poster", "poster"),
                        ],
                        default="Newspaper",
                        max_length=1024,
                        verbose_name="How you Known about csc",
                    ),
                ),
                ("enquiry_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "counsellor_remark",
                    models.TextField(default="", verbose_name="Counsellor Remark"),
                ),
                (
                    "enquiry_statuss",
                    models.CharField(
                        choices=[
                            ("Following", "Following"),
                            ("Admited", "Admited"),
                            ("Rejected", "Rejected"),
                        ],
                        default="following",
                        max_length=1024,
                        verbose_name="Enquiry Status",
                    ),
                ),
            ],
        ),
    ]
