# Generated by Django 5.0 on 2023-12-27 04:22

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enquiry", "0002_remove_enquiry_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enquiry",
            name="enquiry_statuss",
        ),
        migrations.AddField(
            model_name="enquiry",
            name="address",
            field=models.TextField(blank=True, verbose_name="Address"),
        ),
        migrations.AddField(
            model_name="enquiry",
            name="age",
            field=models.IntegerField(blank=True, default=None, verbose_name="Age"),
        ),
        migrations.AddField(
            model_name="enquiry",
            name="date_of_birth",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Date of Birth"
            ),
        ),
        migrations.AddField(
            model_name="enquiry",
            name="enquiry_status",
            field=models.CharField(
                choices=[
                    ("Following", "Following"),
                    ("Admitted", "Admitted"),
                    ("Rejected", "Rejected"),
                ],
                default="Following",
                max_length=1024,
                verbose_name="Enquiry Status",
            ),
        ),
        migrations.AddField(
            model_name="enquiry",
            name="expected_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Expected Date of Join"
            ),
        ),
        migrations.AddField(
            model_name="enquiry",
            name="f_name",
            field=models.CharField(
                default="", max_length=255, verbose_name="Student's Father Name"
            ),
        ),
        migrations.AddField(
            model_name="enquiry",
            name="student_college_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=1055,
                null=True,
                verbose_name="College Name",
            ),
        ),
        migrations.AddField(
            model_name="enquiry",
            name="student_company_name",
            field=models.CharField(
                blank=True,
                max_length=1024,
                null=True,
                verbose_name="If Emloyed Company Name",
            ),
        ),
        migrations.AlterField(
            model_name="enquiry",
            name="counsellor_remark",
            field=models.TextField(
                default="", null=True, verbose_name="Counsellor Remark"
            ),
        ),
        migrations.AlterField(
            model_name="enquiry",
            name="course_to_join",
            field=models.CharField(
                default="", max_length=1024, verbose_name="Course Interested to Join"
            ),
        ),
        migrations.AlterField(
            model_name="enquiry",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                default="male",
                max_length=10,
                verbose_name="Gender",
            ),
        ),
        migrations.AlterField(
            model_name="enquiry",
            name="known_csc",
            field=models.CharField(
                choices=[
                    ("Television", "Television"),
                    ("Newspaper", "Newspaper"),
                    ("Friend recommend", "Friend recommend"),
                    ("Poster", "Poster"),
                ],
                default="Newspaper",
                max_length=1024,
                verbose_name="How You Know about CSC",
            ),
        ),
        migrations.AlterField(
            model_name="enquiry",
            name="mobile_number",
            field=models.CharField(
                blank=True,
                max_length=13,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Entered mobile number isn't in a right format!",
                        regex="^[0-9]{10,15}$",
                    )
                ],
                verbose_name="Mobile Number",
            ),
        ),
        migrations.AlterField(
            model_name="enquiry",
            name="need_of_study",
            field=models.CharField(
                choices=[
                    ("For a job", "For a job"),
                    (
                        "For a job in software profession",
                        "For a job in software profession",
                    ),
                    ("For advance study", "For advance study"),
                    ("Sponsored by company", "Sponsored by company"),
                ],
                default="For a job",
                max_length=1024,
                verbose_name="Reason for Study",
            ),
        ),
        migrations.AlterField(
            model_name="enquiry",
            name="pincode",
            field=models.IntegerField(blank=True, default=None, verbose_name="Pincode"),
        ),
        migrations.AlterField(
            model_name="enquiry",
            name="qualification",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Qualification"
            ),
        ),
        migrations.AlterField(
            model_name="enquiry",
            name="qualification_status",
            field=models.CharField(
                choices=[("Completed", "Completed"), ("Undergoing", "Undergoing")],
                default="Completed",
                max_length=50,
                verbose_name="Qualification Status",
            ),
        ),
        migrations.AlterField(
            model_name="enquiry",
            name="student_role",
            field=models.CharField(
                choices=[
                    ("Employed", "Employed"),
                    ("Unemployed", "Unemployed"),
                    ("Housewife", "Housewife"),
                    ("Businessman", "Businessman"),
                    ("Student", "Student"),
                    ("Others", "Others"),
                ],
                default="Student",
                max_length=1024,
                verbose_name="Student Occupation",
            ),
        ),
        migrations.AlterField(
            model_name="enquiry",
            name="studying_course",
            field=models.TextField(
                blank=True, default="", max_length=255, verbose_name="Studying Course"
            ),
        ),
        migrations.AlterField(
            model_name="enquiry",
            name="studying_year",
            field=models.IntegerField(
                default=None, null=True, verbose_name="Studying Year"
            ),
        ),
        migrations.AlterField(
            model_name="enquiry",
            name="time_to_study",
            field=models.CharField(
                default="", max_length=255, verbose_name="Prefered Timing"
            ),
        ),
    ]
