# Generated by Django 5.0 on 2023-12-27 04:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enquiry", "0003_remove_enquiry_enquiry_statuss_enquiry_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="enquiry",
            name="aadhar_no",
            field=models.BigIntegerField(default=None, verbose_name="Aadhar Number"),
        ),
    ]
