# Generated by Django 5.0 on 2023-12-27 05:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enquiry", "0007_alter_enquiry_aadhar_no"),
    ]

    operations = [
        migrations.CreateModel(
            name="Enquirylogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "log_date",
                    models.DateField(
                        default=datetime.datetime(
                            2023, 12, 27, 5, 9, 25, 434490, tzinfo=datetime.timezone.utc
                        ),
                        verbose_name="Enquired Date",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, default=None, null=True, verbose_name="Remark"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="enquiry.enquiry",
                    ),
                ),
            ],
        ),
    ]
