# Generated by Django 5.0 on 2023-12-27 05:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enquiry", "0008_enquirylogs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enquirylogs",
            name="log_date",
            field=models.DateField(auto_now=True, verbose_name="Enquired Date"),
        ),
    ]
