# Generated by Django 5.0 on 2023-12-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enquiry", "0009_alter_enquirylogs_log_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="enquirylogs",
            name="contact_by",
            field=models.CharField(
                choices=[
                    ("Phone", "Phone"),
                    ("Whatsapp", "Whatsapp"),
                    ("Email", "Email"),
                ],
                default="Phone",
                max_length=255,
                verbose_name="Contact By",
            ),
        ),
        migrations.AlterField(
            model_name="enquiry",
            name="studying_course",
            field=models.TextField(
                blank=True, default="", max_length=255, verbose_name="Major"
            ),
        ),
        migrations.AlterField(
            model_name="enquiry",
            name="studying_year",
            field=models.IntegerField(
                default=None, null=True, verbose_name="Student Current year"
            ),
        ),
    ]
