# Generated by Django 5.0 on 2023-12-27 10:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enquiry", "0011_enquirylogs_exp_date_enquirylogs_staff_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enquirylogs",
            name="exp_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Expected date"
            ),
        ),
    ]
