# Generated by Django 5.0 on 2023-12-28 04:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("enquiry", "0013_remove_enquiry_aadhar_no"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enquiry",
            name="age",
        ),
    ]
