# Generated by Django 5.0 on 2023-12-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "enquiry",
            "0015_enquiry_district_enquiry_taluka_alter_enquiry_f_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="enquiry",
            name="district",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="District",
            ),
        ),
        migrations.AlterField(
            model_name="enquiry",
            name="taluka",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="Taluk",
            ),
        ),
    ]
