# Generated by Django 5.0 on 2023-12-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enquiry", "0016_alter_enquiry_district_alter_enquiry_taluka"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enquiry",
            name="district",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="District"
            ),
        ),
    ]
