# Generated by Django 5.0 on 2023-12-31 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enquiry", "0020_enquiry_counsellor"),
        ("staffs", "0010_alter_staff_study_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enquirylogs",
            name="staff_contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="staffs.staff"
            ),
        ),
    ]
