# Generated by Django 5.0.3 on 2024-03-09 13:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enquiry", "0021_alter_enquirylogs_staff_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enquirylogs",
            name="log_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Enquired Date"
            ),
        ),
    ]
