# Generated by Django 5.0.3 on 2024-03-10 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corecode", "0009_time"),
        ("course", "0005_courseexammodel"),
        ("enquiry", "0022_alter_enquirylogs_log_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="enquiry",
            name="new_course",
            field=models.CharField(
                blank=True,
                default="",
                max_length=1024,
                null=True,
                verbose_name="New Courese Intersed",
            ),
        ),
        migrations.AlterField(
            model_name="enquiry",
            name="course_to_join",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="course.coursemodel",
            ),
        ),
        migrations.AlterField(
            model_name="enquiry",
            name="time_to_study",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="corecode.time"
            ),
        ),
    ]
