# Generated by Django 5.0.3 on 2024-03-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enquiry", "0023_enquiry_new_course_alter_enquiry_course_to_join_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="enquiry",
            name="new_time",
            field=models.CharField(
                blank=True,
                default="",
                max_length=1024,
                null=True,
                verbose_name="New Time to study",
            ),
        ),
    ]
