# Generated by Django 5.0.3 on 2024-03-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enquiry", "0025_alter_enquiry_time_to_study"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enquiry",
            name="new_time",
        ),
        migrations.AlterField(
            model_name="enquiry",
            name="new_course",
            field=models.CharField(
                blank=True,
                default="",
                max_length=1024,
                null=True,
                verbose_name="Others",
            ),
        ),
    ]
