# Generated by Django 5.0.3 on 2024-03-13 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enquiry", "0026_remove_enquiry_new_time_alter_enquiry_new_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enquiry",
            name="email",
            field=models.EmailField(
                blank=True, default="", max_length=254, null=True, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="enquiry",
            name="mobile_number",
            field=models.CharField(
                blank=True,
                max_length=13,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Entered mobile number isn't in a right format!",
                        regex="^[0-9]{10,15}$",
                    )
                ],
                verbose_name="Mobile Number",
            ),
        ),
    ]
